highway_styles = Dict(
	"motorway" => Dict("color" => 0xf98d72, "width"=>  6, "spec"=>  "-", "is_polygon" =>  false), #bright blue
	"trunk" => Dict("color" => 0x965748, "width"=>  5, "spec"=>  "-", "is_polygon" =>  false), #brown
	"primary" => Dict("color" => 0xff6868, "width"=>  5, "spec"=>  "-", "is_polygon" =>  false), #orange
	"secondary" => Dict("color" => 0xfc4b4b, "width"=>  4, "spec"=>  "-", "is_polygon" =>  false), #orange-ish red
	"tertiary" => Dict("color" => 0xfc3232, "width"=>  3, "spec"=>  "-", "is_polygon" =>  false), #red
	"unclassified" => Dict("color" => 0xF1EEE8, "width"=>  2, "spec"=>  "-", "is_polygon" =>  false),
	"residential" => Dict("color" => 0xF1EEE8, "width"=>  2, "spec"=>  "-", "is_polygon" =>  false),
	"service" => Dict("color" => 0xfceec7, "width"=>  1, "spec"=>  "-", "is_polygon" =>  false),
	"motorway_link" => Dict("color" => 0xe891a1, "width"=>  2, "spec"=>  "-", "is_polygon" =>  false),
	"trunk_link" => Dict("color" => 0xA9A9A9, "width"=>  2, "spec"=>  "-", "is_polygon" =>  false),
	"primary_link" => Dict("color" => 0xA9A9A9, "width"=>  2, "spec"=>  "-", "is_polygon" =>  false),
	"secondary_link" => Dict("color" => 0xA9A9A9, "width"=>  2, "spec"=>  "-", "is_polygon" =>  false),
	"tertiary_link" => Dict("color" => 0xA9A9A9, "width"=>  2, "spec"=>  "-", "is_polygon" =>  false),
	"living_street" => Dict("color" => 0xF1EEE8, "width"=>  2, "spec"=>  "-", "is_polygon" =>  false),
	"yes" => Dict("color" => 0xF1EEE8, "width"=>  2, "spec"=>  "-", "is_polygon" =>  false),
	"pedestrian" => Dict("color" => 0x888888, "width"=>  2, "spec"=>  "-", "is_polygon" =>  false),
	"pedestrian_area" => Dict("color" => 0x888888, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"track" => Dict("color" => 0x909090, "width"=>  1, "spec"=>  ":", "is_polygon" =>  false),
	"bus_guideway" => Dict("color" => 0x989898, "width"=>  1, "spec"=>  ":", "is_polygon" =>  false),
	"escape" => Dict("color" => 0xA0A0A0, "width"=>  1, "spec"=>  ":", "is_polygon" =>  false),
	"raceway" => Dict("color" => 0xA8A8A8, "width"=>  1, "spec"=>  ":", "is_polygon" =>  false),
	"road" => Dict("color" => 0xA9A9A9, "width"=>  1, "spec"=>  ":", "is_polygon" =>  false),
	"footway" => Dict("color" => 0xB0B0B0, "width"=>  1, "spec"=>  ":", "is_polygon" =>  false),
	"bridleway" => Dict("color" => 0xB8B8B8, "width"=>  1, "spec"=>  ":", "is_polygon" =>  false),
	"steps" => Dict("color" => 0xBEBEBE, "width"=>  1, "spec"=>  ":", "is_polygon" =>  false), 
	"path" => Dict("color" => 0xC0C0C0, "width"=>  1, "spec"=>  ":", "is_polygon" =>  false) 
)
building_styles = Dict(
	"yes" => Dict("color" => 0xe891a1, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"house" => Dict("color" => 0x91f2ce, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"residential" => Dict("color" => 0x91f2ce, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"garage" => Dict("color" => 0x91f2ce, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"apartments" => Dict("color" => 0x91f2ce, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true), #all residential stuff is greenish
	"hut" => Dict("color" => 0xe891a1, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"detached" => Dict("color" => 0xe891a1, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"shed" => Dict("color" => 0x876d6c, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"terrace" => Dict("color" => 0xe891a1, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"garages" => Dict("color" => 0xe891a1, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"school" => Dict("color" => 0xb2effc, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"university" => Dict("color" => 0xb2effc, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true), #schools are blue
	"construction" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"farm" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"hotel" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"dormitory" => Dict("color" => 0xb2effc, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"houseboat" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bungalow" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"static_caravan" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"cabin" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"commercial" => Dict("color" => 0xfcf2b2, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"office" => Dict("color" => 0xfcf2b2, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"industrial" => Dict("color" => 0x876d6c, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"retail" => Dict("color" => 0xfcf2b2, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"supermarket" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"warehouse" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"kiosk" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"religious" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"cathedral" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"chapel" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"church" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"mosque" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"temple" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"synagogue" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"shrine" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bakehouse" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"kindergarten" => Dict("color" => 0xb2effc, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"civic" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"government" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"hospital" => Dict("color" => 0xA9A9A9, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"stadium" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"train_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"transportation" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"university" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"grandstand" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"public" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"toilets" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"barn" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bridge" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bunker" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"carport" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"conservatory" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"cowshed" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"digester" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"farm_auxiliary" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"garbage_shed" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"greenhouse" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"hangar" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"hut" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"pavilion" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"parking" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"riding_hall" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"roof" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"sports_hall" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"stable" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"sty" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"transformer_tower" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"service" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"ruins" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"water_tower" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"tech_cab"  => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"stilt_house" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"sports_centre" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"slurry_tank" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"semidetached_house" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"semi" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"remote_digital_terminal" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"proposed" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"planned" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"marquee" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"manufacture" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"ground_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"exit" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"entrance" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"container" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"condominium" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"college" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"central_office" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"allotment_house" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"brewery" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"boathouse" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"barrack" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
)
waterway_styles = Dict(
	"stream" => Dict("color" => 0x9ec3ff, "width"=>  3, "spec"=>  "-", "is_polygon" =>  false),
	"ditch" => Dict("color" => 0x9ec3ff, "width"=>  1, "spec"=>  "-", "is_polygon" =>  false),
	"river" => Dict("color" => 0x9ec3ff, "width"=>  5, "spec"=>  "-", "is_polygon" =>  false),
	"drain" => Dict("color" => 0x9ec3ff, "width"=>  1, "spec"=>  "-", "is_polygon" =>  false),
	"riverbank" => Dict("color" => 0x9ec3ff, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"canal" => Dict("color" => 0x9ec3ff, "width"=>  1, "spec"=>  "-", "is_polygon" =>  false),
	"other" => Dict("color" => 0x9ec3ff, "width"=>  1, "spec"=>  "-", "is_polygon" =>  false),
	"dock" => Dict("color" => 0x808080, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"boatyard" => Dict("color" => 0x808080, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"dam" => Dict("color" => 0x808080, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
)
leisure_styles = Dict(
	"pitch" => Dict("color" => 0xbff9b6, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"swimming_pool" => Dict("color" => 0x9ec3ff, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"park" => Dict("color" => 0xbff9b6, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"playground" => Dict("color" => 0xbff9b6, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"garden" => Dict("color" => 0xbff9b6, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"sports_centre" => Dict("color" => 0x30bc0d, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"other" => Dict("color" => 0x808080, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
)
nature_styles = Dict(
	"wood" => Dict("color" => 0xADD19E, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"tree_row" => Dict("color" => 0xADD19E, "width"=>  2, "spec"=>  "-", "is_polygon" =>  false),
	"tree" => Dict("color" => 0xADD19E, "width"=>  2, "spec"=>  "-", "is_polygon" =>  false),
	"scrub" => Dict("color" => 0xB5E3B5, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"heath" => Dict("color" => 0xD6D99F, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"grassland" => Dict("color" => 0xC6E4B4, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"bare_rock" => Dict("color" => 0xDAD5D0, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"scree" => Dict("color" => 0xEDE4DC, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"shingle" => Dict("color" => 0xF9F9F9, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"sand" => Dict("color" => 0xF1E5C2, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"mud" => Dict("color" => 0xDDCEC0, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"water" => Dict("color" => 0xF9F9F9, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"wetland" => Dict("color" => 0xF9F9F9, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"glacier" => Dict("color" => 0xDDECEC, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"bay" => Dict("color" => 0xF9F9F9, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),
	"beach" => Dict("color" => 0xFFF1BA, "width"=>  2, "spec"=>  "-", "is_polygon" =>  true),

)
amenity_styles = Dict(
	"administration" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"advertising" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"air_filling" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"alm" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"ambulance_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"animal_boarding" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"animal_breeding" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"animal_shelter" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"architect_office" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"archive" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"arts_centre" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"artwork" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"atm" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"audiologist" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"baby_hatch" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"baking_oven" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bank" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bar" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bbq" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bench" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bicycle_parking" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bicycle_rental" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bicycle_repair_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bicycle_trailer_sharing" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"biergarten" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bikeshed" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"blood_donation" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"boat_rental" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"boat_sharing" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"boat_storage" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"brothel" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bts" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"buggy_parking" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"building_yard" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bureau_de_change" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bus_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"bus_stop" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"cafe" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"canoe_hire" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"car_pooling" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"car_rental" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"car_repair" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"car_sharing" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"car_wash" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"carwash" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"casino" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"charging_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"childcare" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"cinema" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"citymap_post" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"clinic" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"cloakroom" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"clock" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"clothes_dryer" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"club" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"coast_guard" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"coast_radar_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"college" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"community_center" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"community_centre" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"compressed_air" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"concert_hall" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"concession_stand" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"conference_centre" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"courier" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"courthouse" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"coworking_space" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"crematorium" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"crematory" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"crucifix" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"crypt" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"culture_center" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"customs" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"dancing_school" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"dead_pub" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"dentist" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"device_charging_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"disused" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"dive_centre" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"doctor" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"doctors" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"dog_bin" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"dog_waste_bin" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"dojo" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"donation" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"dressing_room" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"drinking_water" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"driving_school" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"dryer" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"education" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"embassy" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"emergency_phone" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"ev_charging" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"events_venue" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"exercise_point" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"exhibition_centre" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"fab_lab" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"fast_food" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"feeding_place" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"ferry_terminal" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"festival_grounds" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"financial_advice" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"fire_hydrant" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"fire_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"first_aid" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"firstaid" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"fish_spa" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"fitness_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"flight_school" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"food_court" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"fountain" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"fridge" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"fuel" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"gambling" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"game_feeding" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"garages" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"grave_yard" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"grit_bin" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"gym" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"harbourmaster" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"hookah_lounge" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"hospice" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"hospital" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"hotel" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"hunting_stand" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"ice_cream" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"internet_cafe" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"jobcentre" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"juice_bar" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"kindergarten" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"kiosk" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"kitchen" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"kneipp_water_cure" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"language_school" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"lavoir" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"letter_box" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"library" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"life_ring" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"lifeboat_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"loading_dock" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"lounger" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"love_hotel" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"marae" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"marketplace" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"medical_supply" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"microwave" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"milk_dispenser" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"mobile_library" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"monastery" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"money_transfer" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"mortuary" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"motorcycle_parking" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"motorcycle_rental" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"music_school" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"music_venue" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"nightclub" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"nursery" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"nursing_home" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"nutritionist" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"office" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"park" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"parking" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"parking_entrance" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"parking_space" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"parkink" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"payment_centre" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"payment_terminal" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"pharmacy" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"photo_booth" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"place_of_worship" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"planetarium" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"police" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"polling_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"post_box" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"post_office" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"preschool" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"printer" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"prison" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"prison_camp" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"proposed" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"pub" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"public_bath" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"public_bookcase" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"public_building" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"ranger_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"reception_desk" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"recycling" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"refugee_housing" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"register_office" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"rescue_box" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"rescue_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"research_institute" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"restaurant" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"retirement_home" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"sanatorium" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"sanitary_dump_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"sauna" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"sceptic_tank" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"school" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"seat" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"security_booth" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"septic_tank" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"shelter" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"shop" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"shower" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"ski_rental" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"ski_school" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"smoking_area" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"snow_removal_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"social_centre" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"social_facility" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"spa" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"stables" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"stool" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"street_lamp" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"street_light" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"stripclub" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"studio" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"swimming_pool" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"swingerclub" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"table" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"taxi" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"taxi_point" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"telephone" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"television" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"theatre" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"ticket_booth" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"ticket_validator" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"toilet" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"toilets" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"townhall" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"training" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"trolley_bay" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"tuition" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"university" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"vacuum_cleaner" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"vehicle_inspection" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"vehicle_ramp" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"vending_machine" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"veterinary" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"veterinary_pharmacy" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"vivarium" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"washing_machine" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"waste_basket" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"waste_disposal" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"waste_transfer_station" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"water" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"watering_place" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"weighbridge" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"winery" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"yacht_club" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
	"youth_centre" => Dict("color" => 0xf2d2d8, "width"=>  1, "spec"=>  "-", "is_polygon" =>  true),
)
tag2style = Dict(
	"waterway" => waterway_styles,
	"building" => building_styles,
	"highway" => highway_styles,
	"leisure" => leisure_styles,
	"nature" => nature_styles,
	"amenity" => amenity_styles,
)
function get_way_style(tags::Dict, cascade::Array{Any})
		if cascade != []
			style = nothing
			for rule in cascade
				d = rule[2]
				if d == Dict()
					style = rule[end]
				end
				for i in keys(d)
					if haskey(tags, i)
						if d[i][1] == "yes"
							style = rule[end]
						end
						operator = d[i][2]
						if operator == "="
							operator = "=="
						end
						if tryparse(Float64, tags[i]) != nothing && tryparse(Float64, d[i][1]) !=nothing
							eval_statement = "$(tags[i])$(operator)$(d[i][1])"
						else 
							eval_statement = "\"$(tags[i])\"$(operator)\"$(d[i][1])\""
						end
						if eval(Meta.parse(eval_statement)) == true
							if style == nothing
								style = rule[end]
							else
								style = merge(style, rule[end])
							end;
						end
					end
				end
			end
			return style
		end
        for tag in ["waterway", "building", "amenity", "highway", "leisure", "nature"]
            if haskey(tags, tag)
                if haskey(tag2style[tag], tags[tag])
                    return tag2style[tag][tags[tag]]
                end
            end
        end
        return Dict("color" => 0xD3D3D3, "width"=>  1, "spec"=>  "-", "is_polygon" =>  false)
    end